New tweet
chiha7777/twitter_clone pull request #4
Opened 2022-09-09 11:47 UTC by chiha7777

tweet機能

2022-09-09 23:50 UTC, kotasuzuki72 approved these changes

2022-09-12 00:22 UTC, TAK848 requested changes
よく出来ています！
何点か修正お願いします！

2022-09-12 00:22 UTC, TAK848 commented on accounts/admin.py
> -# Register your models here.
Userもadminに登録しておきましょう

2022-09-12 00:22 UTC, TAK848 commented on config/settings.py
> +    "tweet.apps.TweetConfig",
1. "accounts"と同じように統一表記で書きましょう（ここでは"tweet"）
2. "accounts"の下に移動しましょう（自作のアプリの位置統一）

2022-09-12 00:22 UTC, TAK848 commented on config/urls.py
> +    path("tweet/", include("tweet.urls")),
`tweets/`にしましょう（テスト要件のシートも参照）

2022-09-12 00:22 UTC, TAK848 commented on templates/tweet/tweet_create.html
> +<a href="{% url 'accounts:home' %}">トップページへ</a>
誘導がわかりやすくて良いと思います！

2022-09-12 00:22 UTC, TAK848 commented on tweet/admin.py
> +# Register your models here.
delete comment

2022-09-12 00:22 UTC, TAK848 commented on templates/tweet/tweet_detail.html
> +  <p>{{object.content}}</p>
context_object_nameをtweetにしているので，tweet.user/tweet.contentとしてあげましょう

2022-09-12 00:22 UTC, TAK848 commented on tweet/views.py
> +    context_object_name = "tweet"
model=Tweetの代わりに，
```python
queryset = Tweet.objects.all().select_related("user")
```
とすると，テンプレートでtweet.userとしたときにSQLの再発行をするのを防げます（パフォーマンスの話）

2022-09-12 00:22 UTC, TAK848 commented on tweet/urls.py
> +    path("tweet/<int:pk>/", views.TweetDetailView.as_view(), name="detail"),
configのurlから読み込んでいるので，
`tweet/tweet/<pk>/`となってしまっています。
`tweet/`は消しましょう

2022-09-12 00:22 UTC, TAK848 commented on templates/accounts/home.html
> +    {% endfor%}
```suggestion
    {% endfor %}
```

2022-09-12 00:22 UTC, TAK848 commented on accounts/views.py
> +        return Tweet.objects.all().select_related("user")
N+1解消出来ていてgoodです！
これだけであれば，
```suggestion
    context_object_name = "tweet_list"
    queryset = Tweet.objects.all().select_related("user")
```
でもOKです

2022-09-12 00:22 UTC, TAK848 commented on accounts/views.py
> +        return render(request, "tweet/tweet_detail.html", {"tweet": tweet})
これ使ってますか？

2022-09-12 09:23 UTC, TAK848 approved these changes
LGTM

2022-09-12 14:00 UTC, merged