follow機能の作成
chiha7777/twitter_clone pull request #5
Opened 2022-12-08 05:16 UTC by chiha7777

2022-12-09 06:50 UTC, tatsurou9003 commented
丁寧にProfileモデルを作成していて素晴らしいと思います、以下の修正お願いします。

2022-12-09 06:55 UTC, tatsurou9003 commented
テスト成功画面のスクリーンショット添付をお願いします。

2022-12-09 07:31 UTC, tatsurou9003 commented on accounts/migrations/0003_profile.py
> +    ]
マイグレーションファイルが多くなってしまっているのでロールバックしてまとめてください。基準としては一機能あたり1つのマイグレーションファイル（Profile機能で1つ、Follow機能で1つ）ですが、面倒だったら全部まとめて1つにして頂いて大丈夫です。

2022-12-09 07:31 UTC, tatsurou9003 commented on templates/accounts/follower_list.html
> +  <button class="btn btn-outline-info" type="submit">{{ follow.follower }}をフォローする</button>
この状態だとフォロー済みの場合でも「フォローする」が出てきてしまっています、場合分けをしてフォロー済みの場合は「フォロー解除」が出るように修正お願いします。

2022-12-09 07:31 UTC, tatsurou9003 commented on accounts/views.py
> +    model = FriendShip
こちらmodelの受け渡しは必要ないので消しちゃって良いと思います。

2022-12-09 07:31 UTC, tatsurou9003 commented on accounts/views.py
> +            messages.success(request, "フォローしました。")
messageの出力が現状テスト時にしか行われていません。templatesの該当ファイルにmessageタグをつけて常時出力されるようにしたほうが親切かなと思います。UnFollowViewも同様です。

2022-12-12 15:52 UTC, chiha7777 commented
<img width="628" alt="スクリーンショット 2022-12-13 0 46 26" src="https://user-images.githubusercontent.com/83357712/207091022-690878b3-9ffc-4e30-9258-7a1db84191ea.png">

2022-12-13 04:55 UTC, tatsurou9003 commented on templates/accounts/follower_list.html
> +{% endif %}
messageタグをつけた際、出力の挙動を確認していますか？今回の場合、フォローする・フォロー解除するのアクションを行った後の遷移先のテンプレートにmessageタグをつけるのが望ましいです。

2022-12-14 07:24 UTC, chiha7777 commented
<img width="608" alt="スクリーンショット 2022-12-14 12 41 25" src="https://user-images.githubusercontent.com/83357712/207531677-7a11a05f-9167-4421-92ec-715548546e9e.png">

2022-12-15 12:39 UTC, TAK848 requested changes
よくできています。数点だけコメントしました！ご確認お願いします！

2022-12-15 12:39 UTC, tak848 commented on accounts/models.py
> +        return f"{self.follower.username} : {self.following.username}"
複合ユニーク制約をつけてください！
viewで同じ組み合わせを防ぐことはできますが，DB（モデル）として付与しましょう！

2022-12-15 12:39 UTC, TAK848 commented on accounts/views.py
> +        return super().get_queryset().select_related("user")
querysetが固定値であれば，これで良さそう
```suggestion
    queryset = Profile.objects.all().select_related("user")
```

2022-12-15 12:39 UTC, tak848 commented on accounts/views.py
> +        ctx = super().get_context_data(*args, **kwargs)
ここは`context`で良いかな

2022-12-15 12:39 UTC, TAK848 commented on accounts/views.py
> +
この空行は意味なさそう

2022-12-15 12:39 UTC, tak848 commented on accounts/views.py
> +        return current_user.pk == self.kwargs["pk"]
userのpkとprofileのpkが同じとは限らないので，
```suggestion
        return current_user.profile.pk == self.kwargs["pk"]
```
が適切かな

2022-12-15 12:39 UTC, TAK848 commented on accounts/views.py
> +            FriendShip.objects.get_or_create(follower=follower, following=following)
101行目でないこと確認しているので，get_or_は要らなそう

2022-12-18 21:31 UTC, TAK848 approved these changes
遅くなりました！LGTMです！！

2022-12-18 21:31 UTC, TAK848 commented on accounts/models.py
> +        ]
good!!

2022-12-23 06:36 UTC, merged